# Generated by Django 4.0.2 on 2022-03-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='project_file',
            field=models.FileField(default=None, upload_to='project_files'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_sites',
            field=models.ManyToManyField(blank=True, to='users.SocialNetwork'),
        ),
    ]
