# Generated by Django 4.0.2 on 2022-03-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userproject_project_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProject',
            new_name='UserProjects',
        ),
    ]
